%{?!ros_distro:%global ros_distro rolling}
%global pkg_name py_trees_ros
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-py-trees-ros
Version:        2.6.0
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            https://py-trees-ros.readthedocs.io/en/release-1.2.x/
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
ROS 2 extensions and behaviours for py_trees.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
ROS 2 extensions and behaviours for py_trees.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
ROS 2 extensions and behaviours for py_trees.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Thu Sep 10 2026 Daniel Stonier <d.stonier@gmail.com> - 2.6.0-1
- Autogenerated by Bloom

* Mon Jul 13 2026 Daniel Stonier <d.stonier@gmail.com> - 2.5.0-1
- Autogenerated by Bloom

* Tue Apr 28 2026 Daniel Stonier <d.stonier@gmail.com> - 2.4.0-3
- Autogenerated by Bloom

* Tue Apr 21 2026 Daniel Stonier <d.stonier@gmail.com> - 2.4.0-1
- Autogenerated by Bloom
