%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-py-trees-ros
Version:        2.3.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS py_trees_ros package

License:        BSD
URL:            https://py-trees-ros.readthedocs.io/en/release-1.2.x/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-py-trees
Requires:       ros-kilted-py-trees-ros-interfaces
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2topic
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2-ros-py
Requires:       ros-kilted-unique-identifier-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-setuptools
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-py-trees
BuildRequires:  ros-kilted-py-trees-ros-interfaces
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ros2topic
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2-ros-py
BuildRequires:  ros-kilted-unique-identifier-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
%endif

%description
ROS2 extensions and behaviours for py_trees.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Daniel Stonier <d.stonier@gmail.com> - 2.3.0-2
- Autogenerated by Bloom

* Sat Jan 11 2025 Daniel Stonier <d.stonier@gmail.com> - 2.3.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Daniel Stonier <d.stonier@gmail.com> - 2.2.2-3
- Autogenerated by Bloom

